-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 18:57:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cms` ;

-- -----------------------------------------------------
-- Schema cms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET utf8 ;
USE `cms` ;

-- -----------------------------------------------------
-- Table `cms`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`session` ;

CREATE TABLE IF NOT EXISTS `cms`.`session` (
  `sessionId` INT NOT NULL,
  `sessionString` VARCHAR(60) NULL,
  `timeStamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sessionUserAgent` VARCHAR(255) NULL,
  PRIMARY KEY (`sessionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`ip` ;

CREATE TABLE IF NOT EXISTS `cms`.`ip` (
  `ipId` INT NOT NULL,
  `ip` VARCHAR(60) NULL,
  `ipisblocked` TINYINT NULL,
  PRIMARY KEY (`ipId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`user` ;

CREATE TABLE IF NOT EXISTS `cms`.`user` (
  `userId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `session_sessionId` INT NOT NULL,
  `ip_ipId` INT NOT NULL,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) ,
  PRIMARY KEY (`userId`, `ip_ipId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) ,
  INDEX `fk_user_session1_idx` (`session_sessionId` ASC) ,
  INDEX `fk_user_ip1_idx` (`ip_ipId` ASC) ,
  CONSTRAINT `fk_user_session1`
    FOREIGN KEY (`session_sessionId`)
    REFERENCES `cms`.`session` (`sessionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_ip1`
    FOREIGN KEY (`ip_ipId`)
    REFERENCES `cms`.`ip` (`ipId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `cms`.`Post_Buttons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`Post_Buttons` ;

CREATE TABLE IF NOT EXISTS `cms`.`Post_Buttons` (
  `post_ButtonsId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_ButtonsType` VARCHAR(45) NULL,
  `Post_ButtonsOrder` INT NULL,
  `Post_ButtonsHref` VARCHAR(45) NULL,
  PRIMARY KEY (`post_ButtonsId`),
  UNIQUE INDEX `post_ButtonsId_UNIQUE` (`post_ButtonsId` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`Post_ParagrafTitels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`Post_ParagrafTitels` ;

CREATE TABLE IF NOT EXISTS `cms`.`Post_ParagrafTitels` (
  `post_ParagrafTitelsId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_ParagrafTitelsText` VARCHAR(45) NULL,
  `post_ParagrafTitelsOrder` INT UNSIGNED NULL,
  PRIMARY KEY (`post_ParagrafTitelsId`),
  UNIQUE INDEX `post_ParagrafTitelsId_UNIQUE` (`post_ParagrafTitelsId` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`post_Images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`post_Images` ;

CREATE TABLE IF NOT EXISTS `cms`.`post_Images` (
  `post_ImagesId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Post_ImagesImglink` VARCHAR(255) NULL,
  `post_ImagesOrder` VARCHAR(45) NULL,
  PRIMARY KEY (`post_ImagesId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`Post_Text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`Post_Text` ;

CREATE TABLE IF NOT EXISTS `cms`.`Post_Text` (
  `post_TextId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_TextText` VARCHAR(45) NULL,
  `post_TextOrder` INT UNSIGNED NULL,
  PRIMARY KEY (`post_TextId`),
  UNIQUE INDEX `post_TextId_UNIQUE` (`post_TextId` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms`.`Post` ;

CREATE TABLE IF NOT EXISTS `cms`.`Post` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `postTitle` VARCHAR(45) NULL,
  `postSubTitle` VARCHAR(45) NULL,
  `Post_Buttons_post_ButtonsId` INT UNSIGNED NOT NULL,
  `Post_ParagrafTitels_post_ParagrafTitelsId` INT UNSIGNED NOT NULL,
  `post_Images_post_ImagesId` INT UNSIGNED NOT NULL,
  `Post_Text_post_TextId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`postId`),
  UNIQUE INDEX `postId_UNIQUE` (`postId` ASC),
  INDEX `fk_Post_Post_Buttons1_idx` (`Post_Buttons_post_ButtonsId` ASC) ,
  INDEX `fk_Post_Post_ParagrafTitels1_idx` (`Post_ParagrafTitels_post_ParagrafTitelsId` ASC) ,
  INDEX `fk_Post_post_Images1_idx` (`post_Images_post_ImagesId` ASC) ,
  INDEX `fk_Post_Post_Text1_idx` (`Post_Text_post_TextId` ASC) ,
  CONSTRAINT `fk_Post_Post_Buttons1`
    FOREIGN KEY (`Post_Buttons_post_ButtonsId`)
    REFERENCES `cms`.`Post_Buttons` (`post_ButtonsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Post_ParagrafTitels1`
    FOREIGN KEY (`Post_ParagrafTitels_post_ParagrafTitelsId`)
    REFERENCES `cms`.`Post_ParagrafTitels` (`post_ParagrafTitelsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_post_Images1`
    FOREIGN KEY (`post_Images_post_ImagesId`)
    REFERENCES `cms`.`post_Images` (`post_ImagesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Post_Text1`
    FOREIGN KEY (`Post_Text_post_TextId`)
    REFERENCES `cms`.`Post_Text` (`post_TextId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
